### ISSUE TITLE
hard coded strings in directory_format are ignored without warning in "esgprep drs"

### ISSUE THREAD

**Issue by alaniwi** [IS-ENES-Data/esgf-prepare#11]
Any hard-coded strings in `directory_format` are ignored - the output data directory is based only on any facets that it contains. This is OK for CMIP6 operations, but during testing for the purpose of familiarising myself with the software, it was very confusing (I inserted a hard-coded string into `directory_format` but the output paths did not change, so then I could not understand how the output path was constructed). If hard-coded strings are encountered (other than the `/` separator), it would be good to issue a warning that they will be ignored.

**Comment by glevava** [comment]
This is a general behavior to the ESGConfigParser library. I already observed it.
Allowing hard-coded parts of the directory format is tricky because some facet cannot be detect by the parser if the "%(...)s" pattern is missing for one of them (because of hard-coded value).
Also difficult to raise a warning and ignore because you should detect that such a pattern is missing and recover the original one without the full regex... : )
I didn't find the best way to proceed to allow users to hard-code some facet values... Any suggestion would be appreciate ; ) Thanks Alan

**Comment by alaniwi** [comment]
I do not think that it is necessary to permit hard-coded parts of the format. Or at least, there is no pressing requirement for it. I simply think that if it is forbidden, then a warning should be issued, so that the user understands that it is not supported.

I am not sure if a simple valid regex for the whole string exists (although I could construct a slightly untidy one), but each directory element ought to conform to a reasonably straightforward regexp, so maybe just do something like:
```
for path_element in directory_format.split("/"):
    if not re.match("%\([A-Za-z_]+\)s$", path_element):
        logging.warn(.......)
        break
```
